kazoo-community/kazoo-ui

whapps/voip/device/device.js

If `audio` is present in the `media` object in device data, but `video` is not, device loading will fail, because the code attempts to check the video codecs when there is no `video` object.

Check for 'video' as well as 'audio' in device.

---

whapps/voip/callflow/callflow.js

Partially from https://github.com/2600hz/kazoo/pull/1265, and because sometimes pivots could 404, pivot_failed messages tell Kazoo callflows to continue. However, Kazoo UI is currently disallowing modules to come after pivot

Allow modules after pivot, as callflow can continue if pivot_failed returned

---

whapps/voip/device/tmpl/edit.html
whapps/voip/device/tmpl/fax.html
whapps/voip/device/tmpl/mobile.html
whapps/voip/device/tmpl/softphone.html
whapps/voip/user/tmpl/edit.html

When viewing a user and editing their devices in the popup window, clicking the caller_id div tab in the foreground currently also changes the background tab

Unique div ids, so background tabs don't change when clicking foreground tabs

---

whapps/voip/user/user.js

Loads up data of the current account and sets the defaults object's timezone default value to that of the working account

Set default timezone for new user to timezone of account

---

index.html

Before this PR, functions called from _amplify.js have a closure that only includes the snapshot of the amplify variable prior to amplify.core.js. Hence, later when the config.js file is loaded and the cache property of the global amplify is set, amplify.module.loadApp and amplify.module.loadModule can never cache bust. This change makes sure that the global amplify is used throughout. Makes the code respect the cache setting in config.js.
Tested thoroughly/used in production over a number of months.

Fix cache busting - incorrect closure within _amplify.js

---

whapps/call_center/dashboard/dashboard.js

The first time this render is called, the calls list won't populate because of the order of these calls

Show calls right away after first render

---

whapps/call_center/dashboard/dashboard.js

Keep on truckin' if a call state in acdc gets into an invalid state (call state doesn't match agent state).

Gracefully handle bad acdc state

---

whapps/numbers/numbers_manager/numbers_manager.js
whapps/pbxs/pbxs_manager/pbxs_manager.js

Recent Kazoo versions duplicate dash_e911 data for a phone number into the e911 field, so use that instead. Then e911 is highlighted for other providers

KAZUI-124: fix highlighting e911 numbers in green for other providers than dash_e911

---

whapps/voip/cdr/cdr.js

The export cdrs by csv was failing for large amounts of data. This is because the CSV was generated by the JS in memory and then returned to the user. If the data grew large enough the web browser would throw a error. 
I have simply removed the generation of the csv from the JS as this can be done through the Crossbar API. In its place it will now just download the csv file directly from the crossbar API.

Master pr improvments to cdr csv export

---

whapps/voip/user/user.js

Empty caller_id_options array loaded from DB was causing issues when saving user details back to DB, with schema expecting caller_id_options as type object
Conflicts:
whapps/voip/user/user.js

Normalize caller_id_options array to object for user

---

whapps/voip/timeofday/timeofday.js
whapps/voip/timeofday/tmpl/edit.html

Previously in the Kazoo-ui there has been no way to set a single time of day that did not repeat yearly. This is helpful for one-time holidays or one-time re-routing of calls. 
This change allows a user to set a single date with a year value to ensure the time-of-day only occurs only once.

Add the ability to set a one-time TIME OF DAY instead of yearly

---

whapps/voip/callflow/callflow.js
whapps/voip/callflow/lang/en.js
whapps/voip/callflow/tmpl/park_callflow.html

This adds a 'Park' module to the call flows which will 'direct park' calls and allows setting a maximum number of "parking" slots. The max slots part of this module requires the back-end change which is currently in PR (https://github.com/2600hz/kazoo/pull/5757).

KAZUI-210: Park call flow module with max slots input

---

whapps/call_center/dashboard/dashboard.js

As of kazoo bb2a98a, even when requesting non-recent statuses, there is a nested timestamp object. Since were are not specifying "recent": true, there's only one key

KAZUI-211: support agent status nested in timestamp object

---

whapps/userportal/portal_manager/css/portal_manager.css
whapps/userportal/portal_manager/lang/en.js
whapps/userportal/portal_manager/lang/nl.js
whapps/userportal/portal_manager/lang/ru.js
whapps/userportal/portal_manager/lang/zh.js
whapps/userportal/portal_manager/portal_manager.js
whapps/userportal/portal_manager/tmpl/transcription.html

**NOTE**: This change requires a Kazoo change (https://github.com/2600hz/kazoo/pull/5863) which is currently in PR.
Once that change is applied to Kazoo then we can use crossbar to pull transcriptions. I have added the ability to view them from the “My Voicemails” list in Kazoo UI. It shows as a chat bubble icon beside the download icon.

KAZUI-222: Added transcriptions dialog to vm list

---

whapps/voip/callflow/callflow.js

I accidentally created this function using the shorthand syntax (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) which is actually not supported in ECMAScript 5, so this function would not work properly with IE9-10. This 1 line changes fixes that issue. Sorry for the oversight.

KAZUI-240: es5/no-shorthand-properties

---

whapps/auth/auth.js

Since the username is normalized to lowercase, it should also be possible to authenticate with any case.

KAZUI-248: authenticate with Kazoo with a case-insensitive username

---

whapps/call_center/dashboard/dashboard.js

Old implementation of callback for first render’s fetch_all_data did only a subset of what render_global_data does, so some things were missing in the dashboard until after the first poll.

KAZUI-257: (call center dashboard) fully render global data on first load

---

config/load.js
index.html
js/amplify/_amplify.js

Generate a new timestamp every minute (instead of every second or millisecond). Use that timestamp when loading language files and whapp/module files.
Also, made the code a bit more DRY.

Use a global cache busting timestamp

---

config/availableApps.js
config/config.js
config/load.js
js/winkstart-request.js
js/winkstart.js

- requires Cache-Control set on HTTP server
- available apps moved to separate file so they are guaranteed to be loaded after the language files (had to be after config because the amplify.cache property is now considered when loading language files)

KAZUI-261: implement proper static content caching

---

js/winkstart-tables.js
whapps/voip/cdr/cdr.js

- consistent ordering of inbound/outbound legs
Backwards compatible, but takes advantage of https://github.com/2600hz/kazoo/pull/6336

KAZUI-277: call history date sort by unix_timestamp_micro

---

whapps/userportal/portal_manager/portal_manager.js

When play is pressed on a voicemail and the status is `new`, it updates the status to `saved`. I attempted to do this via jQuery's `delegate` command but for some reason it does not work with `<audio>` elements in my testing.

KAZUI-281: Change VM to saved upon playing

---

whapps/voip/user/tmpl/edit.html
whapps/voip/user/user.js

- Changed Add Queue type to button so that it’s not also considered a submit type
- Assigned Save button to the user form so that pressing enter on a form input triggers submit (HTML5 Required)
- Brought back parent reference in jQuery selector as it seems to be needed for proper association

KAZUI-287: Fixes to user edit form

---

whapps/voip/vmbox/lang/en.js
whapps/voip/vmbox/lang/nl.js
whapps/voip/vmbox/lang/ru.js
whapps/voip/vmbox/lang/zh.js
whapps/voip/vmbox/tmpl/edit.html
whapps/voip/vmbox/vmbox.js

The "Prepend message on forward" checkbox has been added.

PISTON-1104: Adds vm_message_forward_type form control.

---

.gitattributes

Changes the `.gitattributes` file `* text eof=lf` entry to `* text=auto` to prevent binary files from being seen as having end-of-line changes.
@danielfinke

KAZUI-294: Prevent bogus end-of-line changes.
